root_folder: ./data
method: hoc

# iamcl2r settings
pretrained_model_path: 
- pretrained_models_ckpts/simplex/ckpt_0.pt
- pretrained_models_ckpts/simplex/ckpt_1.pt
- pretrained_models_ckpts/simplex/ckpt_2.pt
replace_ids: 
- 10
- 20

# training settings
increment: 3
